pages:
    stage: deploy
    tags:
        - shell
    rules:
        - if: $CI_COMMIT_BRANCH == 'version'
    script:
        - rm -rf public
        - mkdir public
        - mv docs/* public/
    artifacts:
        paths:
            - public