pages:
    stage: deploy
    tags:
        - shell
    rules:
        - if: $CI_COMMIT_BRANCH == 'version'
    script:
        - git lfs fetch
        - rm -rf public
        - mkdir public
        - mv docs/* public/
        - DATE_STR=$(date +'%Y%m%d')
        - DB_URL=https:\\/\\/gitgud.io\\/umalib\\/UmaLibAndroid\\/-\\/jobs\\/$CI_JOB_ID\\/artifacts\\/raw\\/public\\/$DATE_STR.zip
        - sed -i '' s/TOFILL/$DB_URL/g public/update-info.json
    artifacts:
        paths:
            - public