name: SecretRecover

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Customize trigger events based on your DevSecOps processes.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  Recover:
    runs-on: ubuntu-latest

    steps:
       - name: recover KEY_ALIAS
         run: echo ${KEY_ALIAS} | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k ${MY_OPENSSL_PASSWORD}
         env:
          MY_OPENSSL_ITER: 5
          MY_OPENSSL_PASSWORD: ${{ secrets.MY_OPENSSL_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
       - name: recover KEY_PASSWORD
         run: echo ${KEY_PASSWORD} | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k ${MY_OPENSSL_PASSWORD}
         env:
          MY_OPENSSL_ITER: 5
          MY_OPENSSL_PASSWORD: ${{ secrets.MY_OPENSSL_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
       - name: recover STORE_PASSWORD
         run: echo ${STORE_PASSWORD} | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k ${MY_OPENSSL_PASSWORD}
         env:
          MY_OPENSSL_ITER: 5
          MY_OPENSSL_PASSWORD: ${{ secrets.MY_OPENSSL_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
